# Include per-environment variables
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # CentOS-6.5
        - '{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml'              # RedHat-6.5
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # CentOS-6
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_distribution }}.yml'                                              # CentOS
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
        - 'default.yml'
      paths: '../vars'
  tags: always


# MySQL Server configs
- include_tasks: config.yml
  tags: config

# MySQL Server per OS configs
- include_tasks: "{{ ansible_os_family }}.yml"
  tags: config

# MySQL Server install and settings
- include_tasks: install.yml
  tags: setup

# Create DBs and user
- include_tasks: dbs.yml
  when: mysql_databases|length > 0
  tags:
    - create_dbs
    - setup

# Create only users
- include_tasks: users.yml
  when: mysql_users|length > 0
  tags:
    - create_users
    - setup

- include_tasks: configure_monitoring.yml
  tags: monitoring
  when: monitoring_nagios_enable

- include_tasks: configure_pmm.yml
  tags: monitoring
  when: monitoring_pmm_enable

- include_tasks: configure_logrotate.yml
  tags:
    - config
    - configure_logrotate

# Deploy admin scripts
- include_tasks: script.yml
  tags: script
