---

- name:  mariadb-repo | Adding mariadb repo
  template:
    src:   etc/yum.repos.d/MariaDB.repo.j2
    dest:  /etc/yum.repos.d/MariaDB.repo
    owner: root
    group: root
  register: repo_added
  when:
    - ansible_os_family == 'RedHat'
    - use_satellite_repo == False
