---

- name: RedHat | Install firewalld
  package:
    name: firewalld
    state: present

- name: RedHat | Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_setup

- name: RedHat | Setting firewall rules
  firewalld:
    port:      3306/tcp
    permanent: true
    state:     enabled
    immediate: yes
  when: firewall_setup

- name: RedHat | Install SELinux package
  package:
    name:  "{{ mysql_selinux_package }}"
    state: present
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: RedHat | Set SELinux context on data dir
  sefcontext:
    target: "{{ mysql_data_dir }}(/.*)?"
    setype: mysqld_db_t
    state: present
  register: selinux_datadir
  when:
    - mysql_data_dir != mysql_default_data_dir
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: RedHat | Apply SELinux context on data dir
  command: "restorecon -Rv {{ mysql_data_dir }}"
  when:
    - mysql_data_dir != mysql_default_data_dir
    - selinux_datadir.changed

- name: RedHat | Set SELinux context for log dir
  sefcontext:
    target: "{{ mysql_log_dir }}(/.*)?"
    setype: mysqld_log_t
    state: present
    reload: yes
  register: selinux_logdir
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

- name: RedHat | Set SELinux context on socket
  sefcontext:
    target: "{{ mysql_data_dir }}/mysql.sock"
    setype: mysqld_var_run_t
    state: present
    reload: yes
  when:
    - mysql_data_dir != mysql_default_data_dir
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"

